language: node_js
cache:
directories:
- node_modules
notifications:
email: false
branches:
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: wHEnJNIsw3h4enuDgFpEsuv5uRc9R3jgxX4zoqOWLBTTDqoKx+ryucAb68VHoz01zV47zyGYTnX4hMZffiPvAVwV1I6COO+eG+/5FC7Y3857WQSZtJXic2/7AGq+toELZ2dnze3yN7wjqNu22swTuVVwdbDSNz8XLgeXK9/0SCFRPRKUvGMb0M1AGabysF1VPDWVZdobZyMil4Q1y5pWC3pntG9q7eiKZbuU4SNkHiAVTMg5lL9PI6koOc7iX9JEjNrKEdSlF2IZHu/KwrYctWxRgNQ8zko1y1+Ajyg/0b6w7mDkWNc9EBg5e62lgqEkrBeHGFICb7N++i8ih3yQB4k/brs6tMQ9tDGWbbzl/O8i9IvY6r9oRcCjWUIM120OF15vlZxl7SbTNt9Kk5Ga6o/YCizr9CjFAD7Mas934+DFu3l2GjKTKdyfBYWO2OM4bR3bYZAeadNxGvXzTcSJNtUsrpDgXYfM5DMKCGiEcJeoVHvOtdQyPER90ag7pISgArHNlDZPo3wQc3uDjCXdj1byyfZRc35ZVj2KsqwXvNrPFPu10LQn2HQ5y2gYi5wfDPKQJ7I3224naOmHhQtSdi9bybRl/6a6ppr4ypOFTp6ZXlqEbp5oST2ThR4tMUTepPSjG9uwKuG/omBAB3QoAya/+HSzdb/SJO7L1leNn4U=
